import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/lib/providers/QueryProvider";
import Header from "@/ui/components/header/header";
import ModalEpisodio from "@/ui/components/modals/modalEpisodio";
import ModalLocal from "@/ui/components/modals/modalLocal";
import ModalPersonagem from "@/ui/components/modals/modalPersonagem";
import Footer from "@/ui/components/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <QueryProvider>
          {children}

          <ModalEpisodio />
          <ModalLocal />
          <ModalPersonagem />

          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
